#!/bin/bash

DIR=$(dirname $0)

mkdir -p out

~/.local/share/uv/tools/domdiv/bin/dominion_cricut_svg \
-c $DIR/mropts \
--outfile=out/cut/cut.pdf \
--expansions="$@"

~/.local/share/uv/tools/domdiv/bin/dominion_dividers \
-c $DIR/mropts \
--expansions="$@"
